FROM node:18-alpine

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install -g react-scripts
RUN npm install

COPY . .

EXPOSE 3000

ENV WATCHPACK_POLLING=true

CMD ["npm", "start"]