FROM rust:1.88-slim AS builder

# Install required build dependencies
RUN apt-get update && \
    apt-get install -y \
    pkg-config \
    libssl-dev \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Install cargo-watch for live reloading, rustfmt and sea-orm-cli
RUN cargo install cargo-watch && \
    cargo install sea-orm-cli && \
    rustup component add rustfmt

COPY . .

EXPOSE 3001

# Run with cargo-watch to enable live reloading
RUN mkdir -p /data
RUN touch /data/app.db

CMD ["cargo", "watch", "-i", "data/*", "-i", "../*.db", "-i", "../app.db", "-x", "run", "--poll"]
