FROM rust:1.81

WORKDIR /app

# Install cargo-watch for live reloading, rustfmt and sea-orm-cli
RUN cargo install cargo-watch && \
    cargo install sea-orm-cli && \
    rustup component add rustfmt

COPY . .

EXPOSE 3001

# Run with cargo-watch to enable live reloading
CMD ["cargo", "watch", "-x", "run", "--poll"]